import {recordSubmission,finishSubmission} from '../../../lib/submissions';
type Pair={chainId:string;dexId:string;baseToken:{address:string;name:string;symbol:string};marketCap?:number;fdv?:number;liquidity?:{usd:number};volume?:{h24:number};priceChange?:{h24:number};txns?:{h24:{buys:number;sells:number}};url:string};
async function get(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error('Feed unavailable');return r.json() as Promise<Pair[] & {pairs:Pair[]}>;}
function norm(p:Pair){return {address:p.baseToken.address,name:p.baseToken.name,symbol:p.baseToken.symbol,cap:p.marketCap??p.fdv??null,liquidity:p.liquidity?.usd??null,volume:p.volume?.h24??null,change:p.priceChange?.h24??null,buys:p.txns?.h24?.buys??null,sells:p.txns?.h24?.sells??null,url:p.url};}
let lastFeed:{tokens:ReturnType<typeof norm>[];at:string}|null=null;
export async function GET(req:Request){try{const address=new URL(req.url).searchParams.get('address');if(address){if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address))return Response.json({error:'Invalid Solana address.'},{status:400});const pairs:Pair[]=await get('https://api.dexscreener.com/token-pairs/v1/solana/'+address);const p=pairs.filter(p=>p.chainId==='solana'&&p.baseToken.address===address).sort((a,b)=>(b.liquidity?.usd??0)-(a.liquidity?.usd??0))[0];if(!p)return Response.json({error:'No indexed market found yet. Try again after trading starts.'},{status:404});const t=norm(p);let score=50;const reasons:string[]=[];if(t.liquidity===null)reasons.push('Liquidity unavailable.');else if(t.liquidity<10000){score-=30;reasons.push('Thin liquidity: below $10,000.');}else if(t.liquidity>=50000){score+=15;reasons.push('Liquidity exceeds $50,000.');}else reasons.push('Liquidity below $50,000.');if(t.volume!==null&&t.volume>=50000){score+=10;reasons.push('24h volume exceeds $50,000.');}if(t.change!==null&&t.change < -20){score-=20;reasons.push('Price fell more than 20% in 24h.');}if(t.buys!==null&&t.sells!==null&&t.buys+t.sells>0){if(t.buys>t.sells){score+=10;reasons.push('More buys than sells in 24h.');}else{score-=10;reasons.push('Sells outnumber buys in 24h.');}}if(t.change!==null&&t.change>200){score-=10;reasons.push('Extreme price spike: volatility warning.');}return Response.json({token:t,score:Math.max(0,Math.min(100,score)),verdict:t.liquidity===null?'UNKNOWN':score>=65?'APPROVED':'DISAPPROVED',reasons,method:'Rule-based market signals',at:new Date().toISOString()},{headers:{'Cache-Control':'public,max-age=30'}});}const feeds=await Promise.allSettled(['pumpswap','pumpfun','pump.fun'].map(q=>get('https://api.dexscreener.com/latest/dex/search?q='+q)));const pairs=feeds.flatMap(f=>f.status==='fulfilled'&&Array.isArray(f.value.pairs)?f.value.pairs:[]);const seen=new Set<string>();const tokens=pairs.filter(p=>p.chainId==='solana'&&(/pump/i.test(p.dexId)||p.baseToken.address.endsWith('pump'))).sort((a,b)=>(b.priceChange?.h24??-Infinity)-(a.priceChange?.h24??-Infinity)).filter(p=>{if(seen.has(p.baseToken.address))return false;seen.add(p.baseToken.address);return true;}).slice(0,8).map(norm);if(tokens.length){lastFeed={tokens,at:new Date().toISOString()};return Response.json({...lastFeed,stale:false},{headers:{'Cache-Control':'public,max-age=30'}});}if(lastFeed)return Response.json({...lastFeed,stale:true},{headers:{'Cache-Control':'no-store'}});return Response.json({error:'Live market feed temporarily unavailable. Please retry.'},{status:502});}catch{return Response.json({error:'Live market feed temporarily unavailable. Please retry.'},{status:502});}}




export async function POST(req:Request){
 try{
 const body=await req.json() as {input?:unknown;requestId?:unknown};
 if(typeof body.input!=='string'||body.input.length>512||typeof body.requestId!=='string'||!/^[-a-f0-9]{36}$/i.test(body.requestId))return Response.json({error:'Invalid submission.'},{status:400});
 const input=body.input.trim();let address=input;
 if(input.includes('://')){const u=new URL(input);if(!['pump.fun','www.pump.fun'].includes(u.hostname))return Response.json({error:'Use a pump.fun URL or Solana CA.'},{status:400});address=u.pathname.split('/').filter(Boolean).pop()||'';}
 if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(address))return Response.json({error:'Invalid Solana contract address.'},{status:400});
 let logError:string|undefined;
 try{await recordSubmission(body.requestId,input,address);}catch(e){console.error('Submission save failed',e);logError='Scan history could not be saved. Retry this scan to log it.';}
 const url=new URL(req.url);url.searchParams.set('address',address);
 const response=await GET(new Request(url));const data=await response.json() as {token?:{symbol:string};verdict?:string;error?:string};
 if(!logError){try{await finishSubmission(body.requestId,response.ok?'COMPLETE':'ERROR',data.token?.symbol??null,data.verdict??null);}catch(e){console.error('Submission update failed',e);logError='Scan saved, but its status could not be updated.';}}
 return Response.json({...data,...(logError?{logError}:{})},{status:response.status,headers:{'Cache-Control':'no-store'}});
 }catch{return Response.json({error:'Invalid submission. Please retry.'},{status:400});}
}
