import {apiFetch} from './api';
import {useEffect,useState} from 'react';
type Entry={id:number;input:string;address:string;submittedAt:number;status:string;symbol:string|null;verdict:string|null};
export default function SubmissionLog({refreshKey,onScan,busy}:{refreshKey:number;onScan:(input:string)=>void;busy:boolean}){
 const [entries,setEntries]=useState<Entry[]>([]),[error,setError]=useState(''),[more,setMore]=useState(false),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true;let fetching=false;async function refresh(){if(fetching)return;fetching=true;try{const r=await apiFetch('/api/submissions',{cache:'no-store'});const d=await r.json() as {entries:Entry[];hasMore:boolean;error?:string};if(!r.ok)throw Error(d.error);if(active){setEntries(old=>{const combined=new Map(old.map(e=>[e.id,e]));d.entries.forEach(e=>combined.set(e.id,e));return [...combined.values()].sort((a,b)=>b.id-a.id);});setMore(d.hasMore);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'History unavailable');}finally{fetching=false;}}refresh();const id=setInterval(refresh,5000);return()=>{active=false;clearInterval(id);};},[refreshKey,retry]);
 async function older(){if(!entries.length||loading)return;setLoading(true);try{const r=await apiFetch('/api/submissions?before='+entries[entries.length-1].id);const d=await r.json() as {entries:Entry[];hasMore:boolean;error?:string};if(!r.ok)throw Error(d.error);setEntries(old=>{const combined=new Map(old.map(e=>[e.id,e]));d.entries.forEach(e=>combined.set(e.id,e));return [...combined.values()].sort((a,b)=>b.id-a.id);});setMore(d.hasMore);setError('');}catch(e){setError(e instanceof Error?e.message:'History unavailable');}finally{setLoading(false);}}
 return <section className="submission-log"><div className="log-heading"><div><span className="eyebrow">YOUR SCAN HISTORY</span><h2>What you posted</h2></div><button onClick={()=>setRetry(n=>n+1)}>Refresh</button></div>{error&&<p className="log-error" role="status">{error}</p>}<div className="log-entries">{entries.map(e=><button className="log-entry" key={e.id} disabled={busy} onClick={()=>onScan(e.input)} title="Scan this submission again"><div><span className="log-symbol">{e.symbol?'$'+e.symbol:e.input.startsWith('http')?'PUMP.FUN URL':'SOLANA CA'}</span><time dateTime={new Date(e.submittedAt).toISOString()}>{new Date(e.submittedAt).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></div><code>{e.input}</code><span className={'log-status '+(e.verdict==='APPROVED'?'positive':e.verdict==='DISAPPROVED'?'negative':'')}>{e.verdict||e.status}</span></button>)}{!entries.length&&!error&&<p className="log-empty">The jungle is listening. Your submitted contracts will appear here.</p>}</div>{more&&<button className="load-history" disabled={loading} onClick={older}>{loading?'Loading…':'Older submissions'}</button>}<p className="log-note">Saved in this browser, newest first. Click an entry to scan it again.</p></section>;
}
